### ISSUE TITLE
Valid accounts can be found in the source code

### ISSUE THREAD

**Issue by guillaumeguerin** [entice/web#41]
https://github.com/entice/web/blob/67e1d41dd203d2805e373c0d68b8dd1c13fa30ae/priv/repo/seeds.exs

**Comment by ephe-meral** [comment]
thanks for pointing that out :)
i think this is not a major problem, since these are test accounts anyway and they're basically the only way to test the system right now since we don't have a signup mechanism... iirc

**Comment by ephe-meral** [comment]
so i'm closing this for now.
but if you have a suggestion to improve the situation (such that the community would still have access) please let me know
